### ISSUE TITLE
Add .nvmrc

### ISSUE THREAD

**Issue by marcvangend** [YannickHeeftEenGeleFiets/jira-plugin#1]
I had to nvm-install Node.js v20.17.0 before I could properly build the plugin. Please consider adding an .nvmrc file to specify the expected node version.

**Comment by YannickHeeftEenGeleFiets** [comment]
Fixed in [this commit](https://github.com/YannickHeeftEenGeleFiets/jira-plugin/commit/f8fe11f430260c923c82b217b650bdca6cadbdfb). 👌
