### ISSUE TITLE
Failed to load extension: icon.png is missing

### ISSUE THREAD

**Issue by marcvangend** [YannickHeeftEenGeleFiets/jira-plugin#2]
When trying to install the build, I get the following error:

> File   ~/Code/jira-plugin/dist
> Error    Could not load icon 'icon.png' specified in 'action'.
>               Could not load manifest.

![image](https://github.com/user-attachments/assets/bf3a02d5-24a6-4557-a3cc-1681c5b1a42c)

**Comment by YannickHeeftEenGeleFiets** [comment]
Should be solved [with latest of main](https://github.com/YannickHeeftEenGeleFiets/jira-plugin/commit/f550269471cb150c248f90742cba67899e5e6695).
